#!/bin/bash
#

echo USERNAME=${USERNAME}
echo PASSWORD=${PASSWORD}
echo MAILDOMAIN=${MAILDOMAIN}
echo SMTPSERVER=${SMTPSERVER}
echo SMTPUSERNAME=${SMTPUSERNAME}
echo SMTPPASSWORD=${SMTPPASSWORD}

exec "$@"
